### ISSUE TITLE
Allow for millisecond in Datadog logs timestamp

### ISSUE THREAD

**Issue by dougramirez** [DataDog/opentelemetry-mapping-go#152]
When the @timestamp additional property is set and sent to Datadog milli and nanoseconds are suppressed.  Would it be possible to change the formatting of the field to:

`lr.Timestamp().AsTime().Format(time.RFC3339Nano)`

Instead of:

`lr.Timestamp().AsTime().Format(time.RFC3339)`

https://github.com/DataDog/opentelemetry-mapping-go/blob/1c4a59622fa7b8200f13be09cbd5f60374881559/pkg/otlp/logs/logs_translator.go#L159

**Comment by songy23** [comment]
Chatted offline, as of now Datadog backend doesn’t support nanosecond, but we can look into setting millisecond precision in logs.

**Comment by songy23** [comment]
Fixed in https://github.com/DataDog/opentelemetry-mapping-go/pull/202.
