### ISSUE TITLE
Using resource attributes as tags in the dimensions

### ISSUE THREAD

**Issue by pedro-stanaka** [DataDog/opentelemetry-mapping-go#156]
## Summary

The metric translator has the option to use [ResourceAttributesAsTags](https://github.com/DataDog/opentelemetry-mapping-go/blob/939bdb7d1b57eb8689d6c57425d9650f159a30f9/pkg/otlp/metrics/config.go#L30C2-L30C26), but it is not using that option at all when converting metrics. Is that expected? 

If it is a bug, would you be open to a PR?

**Comment by ringerc** [comment]
Where does this actually take effect?

I've traced `resource_attributes_as_tags` from the DD exporter code:

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/50794afa6b2898515cdab0df2da976716f95e0dd/exporter/datadogexporter/config.go#L239

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/50794afa6b2898515cdab0df2da976716f95e0dd/exporter/datadogexporter/metrics_exporter.go#L68

to this repo, where it's set as:

https://github.com/DataDog/opentelemetry-mapping-go/blob/5432be02915e24c7e8a294cd4a17877016f9b73d/pkg/otlp/metrics/config.go#L99

That sets

https://github.com/DataDog/opentelemetry-mapping-go/blob/5432be02915e24c7e8a294cd4a17877016f9b73d/pkg/otlp/metrics/config.go#L101

`t.ResourceAttributesAsTags` on the `translatorConfig` struct. But this does not appear to be referenced anywhere.

So how does it have any effect?

**Comment by ringerc** [comment]
It looks like the work is really done by https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/resourcetotelemetry via `factory.go` in https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/50794afa6b2898515cdab0df2da976716f95e0dd/exporter/datadogexporter/factory.go#L297

so the code in this repo for `ResourceAttributesAsTags` is probably legacy/meaningless/unfinished.

**Comment by ringerc** [comment]
Datadog does have docs on these mappings, albeit outdated and incomplete:

* https://docs.datadoghq.com/opentelemetry/guide/semantic_mapping/
* https://docs.datadoghq.com/opentelemetry/guide/metrics_mapping/

They aren't easily found though, they're only linked in a "see also" down the bottom of a few of the other otel exporter articles. They're not linked in any of the tagging docs like:

* https://docs.datadoghq.com/getting_started/tagging/
* https://docs.datadoghq.com/getting_started/tagging/using_tags
* https://docs.datadoghq.com/getting_started/tagging/assigning_tags
* https://docs.datadoghq.com/getting_started/tagging/unified_service_tagging
* https://docs.datadoghq.com/opentelemetry/otel_collector_datadog_exporter/?tab=onahost (except in the footer pile of articles)
* https://www.datadoghq.com/blog/tagging-best-practices/

so it's hard to figure out how the datadog exporter for the opentelemetry collector maps the attribute `service.name` to the datadog `service` tag, the `cloud.availability_zone` attribute to `zone` (not for some reason `availability-zone`), etc.

There _is_ a mapping in this repo at https://github.com/DataDog/opentelemetry-mapping-go/tree/main/pkg/otlp/attributes/attributes.go ; it has a bunch of mappings not covered in the above docs, but that's where it's done.

**Comment by songy23** [comment]
The particular config is removed in https://github.com/DataDog/opentelemetry-mapping-go/pull/219.
