### ISSUE TITLE
logs: support setting the source field

### ISSUE THREAD

**Issue by sudomateo** [DataDog/opentelemetry-mapping-go#355]
Support setting the `Ddsource` field on the [`datadogV2.HTTPLogItem`](https://github.com/DataDog/datadog-api-client-go/blob/e7f356b93d37e1d9ea3f5b381ec6d6e650cd3692/api/datadogV2/model_http_log_item.go#L13-L34) struct. The Datadog [Send Logs](https://docs.datadoghq.com/api/latest/logs/#send-logs) API expects the `Ddsource` field to be set in order for log items to have a source.

Currently, the `transform` function sets the `Ddtags`, `Hostname`, `Message`, `Service`, and `AdditionalProperties` fields on the `datadogV2.HTTPLogItem` struct but it does not set the `Ddsource` field.

https://github.com/DataDog/opentelemetry-mapping-go/blob/6e80d7ed923d9daa6a1245c7bc4afff2983fbbe1/pkg/otlp/logs/transform.go#L71

The workaround right now is to use the undocumented `ddtags` attribute to set the `source` tag. Thankfully I was able to find this undocumented attribute in https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/15387#issuecomment-1289094727. Here's the `transform` processor that does that.

```yaml
processors:
  transform:
    log_statements:
      - context: log
        statements:
          - set(attributes["ddtags"], "source:sudomateo")
```

However, even with this configuration the log event will end up with two `source` tags, one with the value defined in the `ddtags` and the other with the value `undefined`. I suspect the `undefined` value is due to the API request not setting the `Ddsource` field which is why I opened this issue. Here's what one would see in the Datadog user interface with the above workaround configuration.

<img width="744" alt="Screenshot 2024-07-02 at 18 49 20" src="https://github.com/DataDog/opentelemetry-mapping-go/assets/24284972/47501928-f71f-4a41-ab64-1225cda8be13">

Please let me know what other information is needed from me. Thank you!

**Comment by brettplarson** [comment]
I'm actually seeing a similar but opposite issue using the under documented ddtags workaround you mentioned here.
![image](https://github.com/user-attachments/assets/83010d3d-9795-43bd-b4de-d32fa2127773)

I would love this as well! It seems very hard to set any of the USM / other commonly used tags in Datadog besides `service`

**Comment by sudomateo** [comment]
Just an FYI I submitted https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/34367 since Datadog Support asked me to submit an issue on that repository instead.
